### ISSUE TITLE
Warnings with very basic case

### ISSUE THREAD

**Issue by mindreframer** [Qqwy/elixir-type_check#46] opened 2021-01-25 14:59 UTC
First: this package looks very promising and I saw how @baldwindavid is using it for his application. This motivated me to play with TypeCheck in my spare time. 

Somehow I get warnings for the most basic example(s) and I am wondering what I'm doing wrong or missing out... 
The same code with normal specs is accepted by Dialyzer, yet is rejected when used with `@spec! / @type!` macros... 

Here is the repo with the failing code: 
- https://github.com/mindreframer/typecheck_issue_reproduction/blob/main/lib/types_example.ex

```elixir
defmodule Input1 do
  use TypeCheck
  defstruct [:to, :from]

  @type! t :: %Input1{from: binary()}
  @spec! run(t()) :: boolean()
  def run(input) do
    IO.inspect(input.from)
    true
  end
end
```

Using latest released version vs. current master branch seems not to make any difference.

So the question would be: is this expected behaviour? The compiled code works OK, it is just that my editor is full with warnings and the message text is very verbose.

**Comment by Qqwy** [comment] 2021-01-26 15:20
> is this expected behaviour? The compiled code works OK, it is just that my editor is full with warnings and the message text is very verbose.

It is not intended behaviour, although it is harmless. 
In the near future (before a stable release) I hope to be able to remove most, if not all, of these warnings.

More information about what is happening here and what can and cannot be done about it was discussed in the previously here:  https://github.com/Qqwy/elixir-type_check/issues/40#issuecomment-744068211 

Your example will provide very useful for me to debug this problem, thank you! :+1:

**Comment by mindreframer** [comment] 2021-01-27 01:51
@Qqwy I see, thank you for the quick response! I really hope there is a way to solve this in a proper way, ignoring (potentially lots of) warnings feels wrong, maybe it's my OCD kicking in, I have to think about it 😄 

Have a nice day and I will probably wait a bit before using type_check.

**Comment by Qqwy** [comment] 2021-09-21 20:19
TypeCheck has had quite some updates in the meantime, and I am happy to say that your example no longer produces any compile-time warnings :-).

I will close this issue; if there is any other problem you encounter, or something I've missed, do not hesitate to open a new one!

**Closed by Qqwy** 2021-09-21 20:19 UTC
Labels: bug

**Comment by mindreframer** [comment] 2021-09-21 20:29
@Qqwy this sounds awesome! I will check it out! Thanks for fixing it!
